In [33]:
import pandas as pd

data = pd.read_csv('titanic.csv')

data

,Pclass,Name,Gendr,Age,SibSp,Parch,Ticket,Embarked,Survived,ticket_date
0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,S,0,1912-01-12
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,C,1,1912-03-29
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,S,1,1912-02-23
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,NaN,1,0,113803,S,1,1912-03-28
4,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,S,0,1912-04-03
...,...,...,...,...,...,...,...,...,...,...
880,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,S,0,1912-01-29
881,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,S,1,1912-03-30
882,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,S,0,1912-04-07
883,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,C,1,1912-03-01
884,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,Q,0,1912-03-05

In [34]:
dt_data = data.drop(['Name','Ticket','ticket_date'], axis = 1)
dt_data

     Pclass   Gendr   Age  SibSp  Parch Embarked  Survived
0         3    male  22.0      1      0        S         0
1         1  female  38.0      1      0        C         1
2         3  female  26.0      0      0        S         1
3         1  female   NaN      1      0        S         1
4         3    male  35.0      0      0        S         0
..      ...     ...   ...    ...    ...      ...       ...
880       2    male  27.0      0      0        S         0
881       1  female  19.0      0      0        S         1
882       3  female  28.0      1      2        S         0
883       1    male  26.0      0      0        C         1
884       3    male  32.0      0      0        Q         0

[885 rows x 7 columns]

In [35]:
data.loc[884]

Pclass                           3
Name           Dooley, Mr. Patrick
Gendr                         male
Age                           32.0
SibSp                            0
Parch                            0
Ticket                      370376
Embarked                         Q
Survived                         0
ticket_date             1912-03-05
Name: 884, dtype: object

In [ ]:
data[data['Embarked'].isna()]

,Pclass,Name,Gendr,Age,SibSp,Parch,Ticket,Embarked,Survived,ticket_date
15,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,NaN,1,1912-03-05
322,3,"Sage, Mr. George John Jr",male,28.0,8,2,CA. 2343,NaN,0,1912-03-26

In [40]:
embarked_na_index = data[data['Embarked'].isna()].index
embarked_na_index

Index([15, 322], dtype='int64')